iqfp_load <- function() {
  source(file.path(harness_root,"R/independent_qdesn_frozen_preprocessing_v10.R"),local=FALSE)
  iqfp_v10_source(repo_root)
}

test_that("saved MCMC replay preserves joint parameter rows and rejects corruption", {
  iqfp_load()
  f <- tempfile(fileext=".csv")
  p <- data.frame(draw=1:4,sigma=1:4,gamma=c(-.1,.1,.2,.3),beta_1=5:8,beta_2=9:12)
  write.csv(p,f,row.names=FALSE)
  x <- iqfp_v10_parameters(f)
  expect_s3_class(x,"exal_mcmc")
  expect_equal(unname(x$summary$beta_mean),c(6.5,10.5))
  a <- exal_posterior_draws(x,3,seed=71)
  b <- exal_posterior_draws(x,3,seed=71)
  expect_equal(a,b)
  expect_equal(a$sigma,p$sigma[a$source_draw_index])
  expect_equal(a$gamma,p$gamma[a$source_draw_index])
  p$sigma[1] <- 0;write.csv(p,f,row.names=FALSE)
  expect_error(iqfp_v10_parameters(f))
  p$sigma[1] <- 1;p$draw[1] <- 2;write.csv(p,f,row.names=FALSE)
  expect_error(iqfp_v10_parameters(f))
})

test_that("effective preprocessing and feature-prefix checks do not trust flags", {
  iqfp_load()
  a <- list(X=matrix(1:6,3,2),states=list(H_all=list(matrix(1:8,4,2))),
    meta=list(lag_center=c(3,3),lag_scale=c(2,2),preprocessing_frozen_from_override=TRUE))
  b <- a
  expect_true(all(iqfp_v10_assert_prefix(a,b,list(center=3,scale=2))$pass))
  b$meta$lag_center[1] <- 4
  expect_error(iqfp_v10_assert_prefix(a,b,list(center=3,scale=2)),"prefix differs")
  b <- a;b$X[1,1] <- b$X[1,1]+.1
  expect_error(iqfp_v10_assert_prefix(a,b,list(center=3,scale=2)))
  b <- a;b$states$H_all[[1]][1,1] <- 9
  expect_error(iqfp_v10_assert_prefix(a,b,list(center=3,scale=2)))
})

test_that("repair configs explicitly separate saved basis from new scientific fits", {
  iqfp_load()
  f <- tempfile(fileext=".json")
  r <- list(job_id="source",case_id="case",pair_role="control",stage="pilot",config_path=f)
  iqfr_v2_write_json(r,f)
  cfg <- iqfp_v10_config(r,"mcmc",repo_root,tempdir())
  expect_identical(cfg$preprocessing_policy,"saved_training_basis_including_observed_warmup")
  expect_identical(cfg$scientific_role,"compatibility_repair_not_article_replacement")
  expect_identical(cfg$reference_config_sha256,iqfr_v2_sha256(f))
  body <- paste(deparse(iqfp_v10_prepare),collapse="\n")
  expect_false(grepl("iqmb_v9_fit_mcmc|exal_mcmc_fit\\(",body))
  expect_match(body,"saved_training_draws",fixed=TRUE)
  expect_match(body,"iqps_v8_fit_check",fixed=TRUE)
})

test_that("the repair launcher waits for dependency completion and parses cleanly", {
  iqfp_load()
  path <- file.path(harness_root,"scripts/run_independent_qdesn_frozen_preprocessing_v10.sh")
  expect_equal(system2("bash",c("-n",path)),0L)
  text <- paste(readLines(path),collapse="\n")
  expect_match(text,"WAITING_FOR_V9_CORES",fixed=TRUE)
  expect_match(text,"BLOCKED_SOURCE_CAMPAIGN",fixed=TRUE)
  expect_match(text,"flock -n",fixed=TRUE)
  expect_match(text,"source_hashes",fixed=TRUE)
})

test_that("closeout preserves estimands, horizon diagnostics and comparator labels", {
  iqfp_load()
  run <- tempfile("replay-closeout-");dir.create(run)
  refpath <- file.path(run,"reference.json")
  cfgpath <- file.path(run,"config.json")
  result <- file.path(run,"result.csv")
  oldpath <- file.path(run,"old.csv")
  status <- file.path(run,"status.json")
  evidence <- file.path(run,"evidence","job");dir.create(evidence,recursive=TRUE)
  ref <- list(result_path=oldpath,horizon=30L)
  cfg <- list(job_id="job",reference_config_path=refpath,status_path=status,
    result_path=result,inference="vb",case_id="case",pair_role="challenger",source_stage="pilot")
  iqfr_v2_write_json(ref,refpath);iqfr_v2_write_json(cfg,cfgpath)
  point <- data.frame(job_id="job",case_id="case",pair_role="challenger",inference="vb",
    estimator="mean_conditional_location",forecast_qtrue_mae=2,
    forecast_qtrue_rmse=3,forecast_check_loss=4)
  iqfr_v2_write_csv(point,result)
  old <- point;old$forecast_qtrue_mae <- 2.5;iqfr_v2_write_csv(old,oldpath)
  draws <- point[rep(1,3),];draws$forecast_qtrue_mae <- c(1,3,5)
  iqfr_v2_write_csv_gz(draws,file.path(evidence,"forecast_metric_draws.csv.gz"))
  granular <- data.frame(estimator=point$estimator,lead=c(1,2,30),
    absolute_oracle_error=c(1,2,3),squared_oracle_error=c(1,4,9),check_loss=c(2,3,4))
  iqfr_v2_write_csv_gz(granular,file.path(evidence,"origin_lead.csv.gz"))
  input <- file.path(evidence,"inputs.csv");manifest <- file.path(evidence,"artifacts.csv")
  iqbs_v5_hash_manifest(c(refpath,oldpath),input)
  iqbs_v5_hash_manifest(c(result,list.files(evidence,full.names=TRUE)),manifest)
  iqfr_v2_write_json(list(status="SUCCESS",manifest=manifest,input_manifest=input),status)
  iqfr_v2_write_csv(data.frame(config_path=cfgpath),file.path(run,"plan.csv"))
  iqfr_v2_write_csv(data.frame(case_id="case",model_variant="dqlm",inference="vb",
    forecast_qtrue_mae=1,forecast_qtrue_rmse=2,forecast_check_loss=3),
    file.path(run,"retained_VB_comparators.csv"))
  iqbs_v5_hash_manifest(cfgpath,file.path(run,"source_hashes.csv"))
  iqbs_v5_hash_manifest(cfgpath,file.path(run,"materialization_hashes.csv"))
  iqfp_v10_closeout(run)
  intervals <- read.csv(file.path(run,"posterior_score_intervals.csv"))
  a <- intervals[intervals$metric=="forecast_qtrue_mae",]
  expect_equal(a$point_score,2)
  expect_equal(a$posterior_score_mean,3)
  expect_equal(c(a$lower,a$upper),unname(quantile(c(1,3,5),c(.025,.975),type=8)))
  horizons <- read.csv(file.path(run,"H1_vs_H30.csv"))
  expect_equal(horizons$pairs,c(1L,3L))
  expect_equal(horizons$forecast_qtrue_mae,c(1,2))
  gaps <- read.csv(file.path(run,"retained_VB_comparator_gaps.csv"))
  expect_true(all(gaps$comparator_inference=="vb"))
  expect_equal(gaps$difference,rep(1,3))
  expect_true(file.info(file.path(run,"old_vs_repaired_review.pdf"))$size>1000)
  expect_false(iqfr_v2_read_json(file.path(run,"closeout.json"))$article_promoted)
  point$forecast_qtrue_mae <- 1.9;iqfr_v2_write_csv(point,result)
  expect_error(iqfp_v10_closeout(run))
})

test_that("health distinguishes real workers, stale flags and invalid evidence", {
  iqfp_load()
  run <- tempfile("replay-health-");dir.create(run)
  artifact <- file.path(run,"artifact.txt");writeLines("original",artifact)
  manifest <- file.path(run,"source_hashes.csv")
  iqbs_v5_hash_manifest(artifact,manifest)
  file.copy(manifest,file.path(run,"materialization_hashes.csv"))
  ids <- c("done","active","stale","failed","pending")
  p <- data.frame(job_id=ids,status_path=file.path(run,paste0(ids,".json")),
    result_path=rep(artifact,5))
  iqfr_v2_write_csv(p,file.path(run,"plan.csv"))
  iqfr_v2_write_json(list(status="SUCCESS",manifest=manifest,input_manifest=manifest),p$status_path[1])
  iqfr_v2_write_json(list(status="RUNNING",pid=Sys.getpid()),p$status_path[2])
  iqfr_v2_write_json(list(status="RUNNING",pid=2147483647L),p$status_path[3])
  iqfr_v2_write_csv(data.frame(job_id="failed",exit_code=17L),file.path(run,"launcher_exit_codes.csv"))
  writeLines(c("status=RUNNING_REPLAY","launcher_pid=2147483647"),file.path(run,"pipeline.status"))
  x <- iqfp_v10_health(run)
  expect_equal(c(x$completed,x$running,x$stale_running,x$failed,x$pending),rep(1L,5))
  expect_true(x$stale_pipeline);expect_false(x$launcher_alive)
  expect_true(x$global_manifests_valid)
  expect_identical(x$jobs$state,c("SUCCESS","RUNNING","STALE_RUNNING","FAILED_BEFORE_STATUS","PENDING"))
  writeLines("changed",artifact)
  x <- iqfp_v10_health(run)
  expect_equal(x$completed,0L);expect_equal(x$invalid,1L)
  expect_false(x$global_manifests_valid)
})

test_that("bounded worker smoke outputs cannot enter production closeout", {
  iqfp_load()
  run <- tempfile("smoke-closeout-");dir.create(run)
  ref <- file.path(run,"reference.json");cfg <- file.path(run,"config.json")
  iqfr_v2_write_json(list(result_path="unused"),ref)
  iqfr_v2_write_json(list(reference_config_path=ref,execution_kind="io_smoke"),cfg)
  iqfr_v2_write_csv(data.frame(config_path=cfg),file.path(run,"plan.csv"))
  for(f in c("source_hashes.csv","materialization_hashes.csv"))
    iqbs_v5_hash_manifest(c(cfg,ref),file.path(run,f))
  expect_error(iqfp_v10_closeout(run),"production")
  expect_error(iqfp_v10_worker(cfg),"identical")
})
