datasets:
  - slug: san_lorenzo_daily
    mode: real
    input_path: /data/muscat_data/jaguir26/data/data_USGS_ppt_soil.csv
    overrides:
      pipeline:
        mode: real
      columns:
        y: USGS
        x: [ppt, soil]
      lags:
        m_y: 365    # use y_{t-1}, y_{t-2}, ..., y_{t-m_y}
        m_x: 365    # use x_t, x_{t-1}, ..., x_{t-m_x}
      split:
        T_use: 3000
        train_prop: 0.9
        use_last: true
      forecast:
        mode: recursive-stochastic
        H_step: 1
        tf_first_k: 0
        paths: 500
