#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  req <- c("yaml")
  need <- setdiff(req, rownames(installed.packages()))
  if (length(need)) install.packages(need, repos = "https://cloud.r-project.org")
  invisible(lapply(req, require, character.only = TRUE))
})

args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(flag, default = NULL) {
  idx <- which(args == flag)
  if (length(idx) && idx < length(args)) args[idx + 1L] else default
}
has_flag <- function(flag) any(args == flag)
`%||%` <- function(a, b) if (is.null(a)) b else a

repo_root <- tryCatch(
  normalizePath(system("git rev-parse --show-toplevel", intern = TRUE), winslash = "/", mustWork = TRUE),
  error = function(...) normalizePath(".", winslash = "/", mustWork = TRUE)
)
setwd(repo_root)

phase <- match.arg(
  as.character(get_arg("--phase", "smoke"))[1L],
  c(
    "smoke",
    "vb",
    "mcmc_ridge",
    "mcmc_rhsns_tt500",
    "mcmc_rhsns_tt5000",
    "failed_mcmc_al",
    "failed_mcmc_exal",
    "failed_mcmc_al_sfreeze",
    "failed_mcmc_exal_sfreeze",
    "failed_mcmc_al_thetafreeze",
    "failed_mcmc_exal_thetafreeze",
    "single_root_probe_exal_tau_only",
    "single_root_probe_exal_theta_tau",
    "single_root_probe_exal_stau",
    "single_root_probe_exal_theta_tau_rescue",
    "representative_triad_exal_tau_only",
    "representative_triad_exal_theta_tau",
    "representative_triad_al_tau_only",
    "representative_triad_al_theta_tau",
    "representative_completion_exal_tau_only",
    "representative_completion_exal_theta_tau",
    "remaining_precision_pair_al_v1",
    "remaining_precision_pair_exal_v2",
    "remaining_precision_matrix_al_qr_v1",
    "remaining_precision_matrix_al_qr_v2",
    "remaining_precision_matrix_al_diag_v1",
    "remaining_precision_matrix_exal_qr_v1",
    "remaining_precision_matrix_exal_qr_v2",
    "remaining_precision_matrix_exal_qr_sig_v1",
    "remaining_precision_matrix_exal_diag_v1",
    "remaining_precision_code_al_ladder_v1",
    "remaining_precision_code_al_ladder_v2",
    "remaining_precision_code_al_eigen_v1",
    "remaining_precision_code_exal_ladder_v1",
    "remaining_precision_code_exal_ladder_v2",
    "remaining_precision_code_exal_eigen_v1",
    "remaining_hard_fail_latent_v_al",
    "remaining_hard_fail_latent_v_exal",
    "remaining_hard_fail_exal_ridge_precision_v1",
    "remaining_hard_fail_exal_ridge_precision_v2",
    "remaining_failed_mcmc_al_v2_canary",
    "remaining_failed_mcmc_exal_v2_canary",
    "remaining_failed_mcmc_al_v2_residual",
    "remaining_failed_mcmc_exal_v2_residual",
    "remaining_failed_mcmc_al_v2",
    "remaining_failed_mcmc_exal_v2",
    "remaining_failed_mcmc_al_v3_rescue_canary",
    "remaining_failed_mcmc_exal_v3_rescue_canary",
    "remaining_failed_mcmc_al_v3_rescue_residual",
    "remaining_failed_mcmc_exal_v3_rescue_residual",
    "remaining_failed_mcmc_al_v3_rescue",
    "remaining_failed_mcmc_exal_v3_rescue",
    "remaining_failed_mcmc_al_v3_rescue_extended_canary",
    "remaining_failed_mcmc_exal_v3_rescue_extended_canary",
    "remaining_failed_mcmc_al_v3_rescue_extended_residual",
    "remaining_failed_mcmc_exal_v3_rescue_extended_residual",
    "remaining_failed_mcmc_al_v3_rescue_extended",
    "remaining_failed_mcmc_exal_v3_rescue_extended",
    "remaining_failed_mcmc_exal_v3_qr_tightslice_canary",
    "remaining_failed_mcmc_exal_v3_qr_tightslice_residual",
    "remaining_failed_mcmc_exal_v3_qr_tightslice",
    "remaining_failed_mcmc_exal_v3_altcore_canary",
    "remaining_failed_mcmc_exal_v3_altcore_residual",
    "remaining_failed_mcmc_exal_v3_altcore",
    "full"
  )
)

phase_defaults_map <- list(
  smoke = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  vb = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  mcmc_ridge = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  mcmc_rhsns_tt500 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  mcmc_rhsns_tt5000 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  failed_mcmc_al = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  failed_mcmc_exal = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml"),
  failed_mcmc_al_sfreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_failed_mcmc_sfreeze_defaults.yaml"),
  failed_mcmc_exal_sfreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_failed_mcmc_sfreeze_defaults.yaml"),
  failed_mcmc_al_thetafreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_failed_mcmc_thetafreeze_defaults.yaml"),
  failed_mcmc_exal_thetafreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_failed_mcmc_thetafreeze_defaults.yaml"),
  single_root_probe_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_tau_only_defaults.yaml"),
  single_root_probe_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_theta_tau_defaults.yaml"),
  single_root_probe_exal_stau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_stau_defaults.yaml"),
  single_root_probe_exal_theta_tau_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_theta_tau_rescue_defaults.yaml"),
  representative_triad_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_triad_tau_only_defaults.yaml"),
  representative_triad_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_triad_theta_tau_defaults.yaml"),
  representative_triad_al_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_triad_tau_only_defaults.yaml"),
  representative_triad_al_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_triad_theta_tau_defaults.yaml"),
  representative_completion_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_completion_exal_tau_only_defaults.yaml"),
  representative_completion_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_completion_exal_theta_tau_defaults.yaml"),
  remaining_precision_pair_al_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_v1_defaults.yaml"),
  remaining_precision_pair_exal_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_v2_defaults.yaml"),
  remaining_precision_matrix_al_qr_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_al_qr_v1_defaults.yaml"),
  remaining_precision_matrix_al_qr_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_al_qr_v2_defaults.yaml"),
  remaining_precision_matrix_al_diag_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_al_diag_v1_defaults.yaml"),
  remaining_precision_matrix_exal_qr_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_exal_qr_v1_defaults.yaml"),
  remaining_precision_matrix_exal_qr_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_exal_qr_v2_defaults.yaml"),
  remaining_precision_matrix_exal_qr_sig_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_exal_qr_sig_v1_defaults.yaml"),
  remaining_precision_matrix_exal_diag_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix_exal_diag_v1_defaults.yaml"),
  remaining_precision_code_al_ladder_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_al_ladder_v1_defaults.yaml"),
  remaining_precision_code_al_ladder_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_al_ladder_v2_defaults.yaml"),
  remaining_precision_code_al_eigen_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_al_eigen_v1_defaults.yaml"),
  remaining_precision_code_exal_ladder_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_exal_ladder_v1_defaults.yaml"),
  remaining_precision_code_exal_ladder_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_exal_ladder_v2_defaults.yaml"),
  remaining_precision_code_exal_eigen_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_exal_eigen_v1_defaults.yaml"),
  remaining_hard_fail_latent_v_al = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_latent_v_al_defaults.yaml"),
  remaining_hard_fail_latent_v_exal = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_latent_v_exal_defaults.yaml"),
  remaining_hard_fail_exal_ridge_precision_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_exal_ridge_precision_v1_defaults.yaml"),
  remaining_hard_fail_exal_ridge_precision_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_exal_ridge_precision_v2_defaults.yaml"),
  remaining_failed_mcmc_al_v2_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_exal_v2_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_al_v2_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_exal_v2_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_al_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_exal_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue_extended_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue_extended_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_al_v3_rescue_extended = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_rescue_extended = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_rescue_extended_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_qr_tightslice_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_qr_tightslice_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_qr_tightslice = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_qr_tightslice_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_altcore_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_altcore_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_altcore_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_altcore_defaults.yaml"),
  remaining_failed_mcmc_exal_v3_altcore = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_exal_altcore_defaults.yaml"),
  full = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_defaults.yaml")
)
phase_grid_map <- list(
  smoke = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_smoke_grid.csv"),
  vb = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.csv"),
  mcmc_ridge = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_mcmc_ridge_grid.csv"),
  mcmc_rhsns_tt500 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_mcmc_rhsns_tt500_grid.csv"),
  mcmc_rhsns_tt5000 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_mcmc_rhsns_tt5000_grid.csv"),
  failed_mcmc_al = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_al_grid.csv"),
  failed_mcmc_exal = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_exal_grid.csv"),
  failed_mcmc_al_sfreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_al_grid.csv"),
  failed_mcmc_exal_sfreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_exal_grid.csv"),
  failed_mcmc_al_thetafreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_al_grid.csv"),
  failed_mcmc_exal_thetafreeze = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_exal_grid.csv"),
  single_root_probe_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_primary_exal_rhsns_grid.csv"),
  single_root_probe_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_primary_exal_rhsns_grid.csv"),
  single_root_probe_exal_stau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_primary_exal_rhsns_grid.csv"),
  single_root_probe_exal_theta_tau_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_primary_exal_rhsns_grid.csv"),
  representative_triad_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_triad_exal_grid.csv"),
  representative_triad_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_triad_exal_grid.csv"),
  representative_triad_al_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_triad_al_grid.csv"),
  representative_triad_al_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_triad_al_grid.csv"),
  representative_completion_exal_tau_only = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_completion_exal_ridge_grid.csv"),
  representative_completion_exal_theta_tau = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_representative_completion_exal_ridge_grid.csv"),
  remaining_precision_pair_al_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_pair_exal_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_matrix_al_qr_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_matrix_al_qr_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_matrix_al_diag_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_matrix_exal_qr_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_matrix_exal_qr_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_matrix_exal_qr_sig_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_matrix_exal_diag_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_code_al_ladder_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_code_al_ladder_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_code_al_eigen_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_al_grid.csv"),
  remaining_precision_code_exal_ladder_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_code_exal_ladder_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_precision_code_exal_eigen_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_exal_grid.csv"),
  remaining_hard_fail_latent_v_al = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_latent_v_al_grid.csv"),
  remaining_hard_fail_latent_v_exal = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_latent_v_exal_grid.csv"),
  remaining_hard_fail_exal_ridge_precision_v1 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_exal_ridge_precision_grid.csv"),
  remaining_hard_fail_exal_ridge_precision_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_hard_fail_exal_ridge_precision_grid.csv"),
  remaining_failed_mcmc_al_v2_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v2_canary_grid.csv"),
  remaining_failed_mcmc_exal_v2_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v2_canary_grid.csv"),
  remaining_failed_mcmc_al_v2_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v2_residual_grid.csv"),
  remaining_failed_mcmc_exal_v2_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v2_residual_grid.csv"),
  remaining_failed_mcmc_al_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v2_grid.csv"),
  remaining_failed_mcmc_exal_v2 = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v2_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_canary_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_canary_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_residual_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_residual_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue_extended_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_canary_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_canary_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue_extended_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_residual_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_residual_grid.csv"),
  remaining_failed_mcmc_al_v3_rescue_extended = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_al_v3_grid.csv"),
  remaining_failed_mcmc_exal_v3_rescue_extended = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_grid.csv"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_canary_grid.csv"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_residual_grid.csv"),
  remaining_failed_mcmc_exal_v3_qr_tightslice = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_grid.csv"),
  remaining_failed_mcmc_exal_v3_altcore_canary = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_canary_grid.csv"),
  remaining_failed_mcmc_exal_v3_altcore_residual = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_residual_grid.csv"),
  remaining_failed_mcmc_exal_v3_altcore = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_exal_v3_grid.csv"),
  full = file.path("config", "validation", "qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.csv")
)
phase_methods_map <- list(
  smoke = "vb,mcmc",
  vb = "vb",
  mcmc_ridge = "mcmc",
  mcmc_rhsns_tt500 = "mcmc",
  mcmc_rhsns_tt5000 = "mcmc",
  failed_mcmc_al = "mcmc",
  failed_mcmc_exal = "mcmc",
  failed_mcmc_al_sfreeze = "mcmc",
  failed_mcmc_exal_sfreeze = "mcmc",
  failed_mcmc_al_thetafreeze = "mcmc",
  failed_mcmc_exal_thetafreeze = "mcmc",
  single_root_probe_exal_tau_only = "mcmc",
  single_root_probe_exal_theta_tau = "mcmc",
  single_root_probe_exal_stau = "mcmc",
  single_root_probe_exal_theta_tau_rescue = "mcmc",
  representative_triad_exal_tau_only = "mcmc",
  representative_triad_exal_theta_tau = "mcmc",
  representative_triad_al_tau_only = "mcmc",
  representative_triad_al_theta_tau = "mcmc",
  representative_completion_exal_tau_only = "mcmc",
  representative_completion_exal_theta_tau = "mcmc",
  remaining_precision_pair_al_v1 = "mcmc",
  remaining_precision_pair_exal_v2 = "mcmc",
  remaining_precision_matrix_al_qr_v1 = "mcmc",
  remaining_precision_matrix_al_qr_v2 = "mcmc",
  remaining_precision_matrix_al_diag_v1 = "mcmc",
  remaining_precision_matrix_exal_qr_v1 = "mcmc",
  remaining_precision_matrix_exal_qr_v2 = "mcmc",
  remaining_precision_matrix_exal_qr_sig_v1 = "mcmc",
  remaining_precision_matrix_exal_diag_v1 = "mcmc",
  remaining_precision_code_al_ladder_v1 = "mcmc",
  remaining_precision_code_al_ladder_v2 = "mcmc",
  remaining_precision_code_al_eigen_v1 = "mcmc",
  remaining_precision_code_exal_ladder_v1 = "mcmc",
  remaining_precision_code_exal_ladder_v2 = "mcmc",
  remaining_precision_code_exal_eigen_v1 = "mcmc",
  remaining_hard_fail_latent_v_al = "mcmc",
  remaining_hard_fail_latent_v_exal = "mcmc",
  remaining_hard_fail_exal_ridge_precision_v1 = "mcmc",
  remaining_hard_fail_exal_ridge_precision_v2 = "mcmc",
  remaining_failed_mcmc_al_v2_canary = "mcmc",
  remaining_failed_mcmc_exal_v2_canary = "mcmc",
  remaining_failed_mcmc_al_v2_residual = "mcmc",
  remaining_failed_mcmc_exal_v2_residual = "mcmc",
  remaining_failed_mcmc_al_v2 = "mcmc",
  remaining_failed_mcmc_exal_v2 = "mcmc",
  remaining_failed_mcmc_al_v3_rescue_canary = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue_canary = "mcmc",
  remaining_failed_mcmc_al_v3_rescue_residual = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue_residual = "mcmc",
  remaining_failed_mcmc_al_v3_rescue = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue = "mcmc",
  remaining_failed_mcmc_al_v3_rescue_extended_canary = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = "mcmc",
  remaining_failed_mcmc_al_v3_rescue_extended_residual = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = "mcmc",
  remaining_failed_mcmc_al_v3_rescue_extended = "mcmc",
  remaining_failed_mcmc_exal_v3_rescue_extended = "mcmc",
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = "mcmc",
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = "mcmc",
  remaining_failed_mcmc_exal_v3_qr_tightslice = "mcmc",
  remaining_failed_mcmc_exal_v3_altcore_canary = "mcmc",
  remaining_failed_mcmc_exal_v3_altcore_residual = "mcmc",
  remaining_failed_mcmc_exal_v3_altcore = "mcmc",
  full = "vb,mcmc"
)
phase_likelihoods_map <- list(
  smoke = NULL,
  vb = NULL,
  mcmc_ridge = NULL,
  mcmc_rhsns_tt500 = NULL,
  mcmc_rhsns_tt5000 = NULL,
  failed_mcmc_al = "al",
  failed_mcmc_exal = "exal",
  failed_mcmc_al_sfreeze = "al",
  failed_mcmc_exal_sfreeze = "exal",
  failed_mcmc_al_thetafreeze = "al",
  failed_mcmc_exal_thetafreeze = "exal",
  single_root_probe_exal_tau_only = "exal",
  single_root_probe_exal_theta_tau = "exal",
  single_root_probe_exal_stau = "exal",
  single_root_probe_exal_theta_tau_rescue = "exal",
  representative_triad_exal_tau_only = "exal",
  representative_triad_exal_theta_tau = "exal",
  representative_triad_al_tau_only = "al",
  representative_triad_al_theta_tau = "al",
  representative_completion_exal_tau_only = "exal",
  representative_completion_exal_theta_tau = "exal",
  remaining_precision_pair_al_v1 = "al",
  remaining_precision_pair_exal_v2 = "exal",
  remaining_precision_matrix_al_qr_v1 = "al",
  remaining_precision_matrix_al_qr_v2 = "al",
  remaining_precision_matrix_al_diag_v1 = "al",
  remaining_precision_matrix_exal_qr_v1 = "exal",
  remaining_precision_matrix_exal_qr_v2 = "exal",
  remaining_precision_matrix_exal_qr_sig_v1 = "exal",
  remaining_precision_matrix_exal_diag_v1 = "exal",
  remaining_precision_code_al_ladder_v1 = "al",
  remaining_precision_code_al_ladder_v2 = "al",
  remaining_precision_code_al_eigen_v1 = "al",
  remaining_precision_code_exal_ladder_v1 = "exal",
  remaining_precision_code_exal_ladder_v2 = "exal",
  remaining_precision_code_exal_eigen_v1 = "exal",
  remaining_hard_fail_latent_v_al = "al",
  remaining_hard_fail_latent_v_exal = "exal",
  remaining_hard_fail_exal_ridge_precision_v1 = "exal",
  remaining_hard_fail_exal_ridge_precision_v2 = "exal",
  remaining_failed_mcmc_al_v2_canary = "al",
  remaining_failed_mcmc_exal_v2_canary = "exal",
  remaining_failed_mcmc_al_v2_residual = "al",
  remaining_failed_mcmc_exal_v2_residual = "exal",
  remaining_failed_mcmc_al_v2 = "al",
  remaining_failed_mcmc_exal_v2 = "exal",
  remaining_failed_mcmc_al_v3_rescue_canary = "al",
  remaining_failed_mcmc_exal_v3_rescue_canary = "exal",
  remaining_failed_mcmc_al_v3_rescue_residual = "al",
  remaining_failed_mcmc_exal_v3_rescue_residual = "exal",
  remaining_failed_mcmc_al_v3_rescue = "al",
  remaining_failed_mcmc_exal_v3_rescue = "exal",
  remaining_failed_mcmc_al_v3_rescue_extended_canary = "al",
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = "exal",
  remaining_failed_mcmc_al_v3_rescue_extended_residual = "al",
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = "exal",
  remaining_failed_mcmc_al_v3_rescue_extended = "al",
  remaining_failed_mcmc_exal_v3_rescue_extended = "exal",
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = "exal",
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = "exal",
  remaining_failed_mcmc_exal_v3_qr_tightslice = "exal",
  remaining_failed_mcmc_exal_v3_altcore_canary = "exal",
  remaining_failed_mcmc_exal_v3_altcore_residual = "exal",
  remaining_failed_mcmc_exal_v3_altcore = "exal",
  full = NULL
)
phase_workers_map <- list(
  smoke = 2L,
  vb = 6L,
  mcmc_ridge = 3L,
  mcmc_rhsns_tt500 = 3L,
  mcmc_rhsns_tt5000 = 2L,
  failed_mcmc_al = 3L,
  failed_mcmc_exal = 3L,
  failed_mcmc_al_sfreeze = 2L,
  failed_mcmc_exal_sfreeze = 2L,
  failed_mcmc_al_thetafreeze = 2L,
  failed_mcmc_exal_thetafreeze = 2L,
  single_root_probe_exal_tau_only = 1L,
  single_root_probe_exal_theta_tau = 1L,
  single_root_probe_exal_stau = 1L,
  single_root_probe_exal_theta_tau_rescue = 1L,
  representative_triad_exal_tau_only = 1L,
  representative_triad_exal_theta_tau = 1L,
  representative_triad_al_tau_only = 1L,
  representative_triad_al_theta_tau = 1L,
  representative_completion_exal_tau_only = 1L,
  representative_completion_exal_theta_tau = 1L,
  remaining_precision_pair_al_v1 = 1L,
  remaining_precision_pair_exal_v2 = 1L,
  remaining_precision_matrix_al_qr_v1 = 1L,
  remaining_precision_matrix_al_qr_v2 = 1L,
  remaining_precision_matrix_al_diag_v1 = 1L,
  remaining_precision_matrix_exal_qr_v1 = 1L,
  remaining_precision_matrix_exal_qr_v2 = 1L,
  remaining_precision_matrix_exal_qr_sig_v1 = 1L,
  remaining_precision_matrix_exal_diag_v1 = 1L,
  remaining_precision_code_al_ladder_v1 = 1L,
  remaining_precision_code_al_ladder_v2 = 1L,
  remaining_precision_code_al_eigen_v1 = 1L,
  remaining_precision_code_exal_ladder_v1 = 1L,
  remaining_precision_code_exal_ladder_v2 = 1L,
  remaining_precision_code_exal_eigen_v1 = 1L,
  remaining_hard_fail_latent_v_al = 3L,
  remaining_hard_fail_latent_v_exal = 2L,
  remaining_hard_fail_exal_ridge_precision_v1 = 2L,
  remaining_hard_fail_exal_ridge_precision_v2 = 2L,
  remaining_failed_mcmc_al_v2_canary = 2L,
  remaining_failed_mcmc_exal_v2_canary = 2L,
  remaining_failed_mcmc_al_v2_residual = 3L,
  remaining_failed_mcmc_exal_v2_residual = 3L,
  remaining_failed_mcmc_al_v2 = 3L,
  remaining_failed_mcmc_exal_v2 = 3L,
  remaining_failed_mcmc_al_v3_rescue_canary = 2L,
  remaining_failed_mcmc_exal_v3_rescue_canary = 2L,
  remaining_failed_mcmc_al_v3_rescue_residual = 1L,
  remaining_failed_mcmc_exal_v3_rescue_residual = 2L,
  remaining_failed_mcmc_al_v3_rescue = 2L,
  remaining_failed_mcmc_exal_v3_rescue = 2L,
  remaining_failed_mcmc_al_v3_rescue_extended_canary = 2L,
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = 2L,
  remaining_failed_mcmc_al_v3_rescue_extended_residual = 1L,
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = 2L,
  remaining_failed_mcmc_al_v3_rescue_extended = 2L,
  remaining_failed_mcmc_exal_v3_rescue_extended = 2L,
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = 2L,
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = 2L,
  remaining_failed_mcmc_exal_v3_qr_tightslice = 2L,
  remaining_failed_mcmc_exal_v3_altcore_canary = 2L,
  remaining_failed_mcmc_exal_v3_altcore_residual = 2L,
  remaining_failed_mcmc_exal_v3_altcore = 2L,
  full = 3L
)
phase_is_subset <- phase %in% c(
  "smoke",
  "mcmc_ridge",
  "mcmc_rhsns_tt500",
  "mcmc_rhsns_tt5000",
  "failed_mcmc_al",
  "failed_mcmc_exal",
  "failed_mcmc_al_sfreeze",
  "failed_mcmc_exal_sfreeze",
  "failed_mcmc_al_thetafreeze",
  "failed_mcmc_exal_thetafreeze",
  "single_root_probe_exal_tau_only",
  "single_root_probe_exal_theta_tau",
  "single_root_probe_exal_stau",
  "single_root_probe_exal_theta_tau_rescue",
  "representative_triad_exal_tau_only",
  "representative_triad_exal_theta_tau",
  "representative_triad_al_tau_only",
  "representative_triad_al_theta_tau",
  "representative_completion_exal_tau_only",
  "representative_completion_exal_theta_tau",
  "remaining_precision_pair_al_v1",
  "remaining_precision_pair_exal_v2",
  "remaining_precision_matrix_al_qr_v1",
  "remaining_precision_matrix_al_qr_v2",
  "remaining_precision_matrix_al_diag_v1",
  "remaining_precision_matrix_exal_qr_v1",
  "remaining_precision_matrix_exal_qr_v2",
  "remaining_precision_matrix_exal_qr_sig_v1",
  "remaining_precision_matrix_exal_diag_v1",
  "remaining_precision_code_al_ladder_v1",
  "remaining_precision_code_al_ladder_v2",
  "remaining_precision_code_al_eigen_v1",
  "remaining_precision_code_exal_ladder_v1",
  "remaining_precision_code_exal_ladder_v2",
  "remaining_precision_code_exal_eigen_v1",
  "remaining_hard_fail_latent_v_al",
  "remaining_hard_fail_latent_v_exal",
  "remaining_hard_fail_exal_ridge_precision_v1",
  "remaining_hard_fail_exal_ridge_precision_v2",
  "remaining_failed_mcmc_al_v2_canary",
  "remaining_failed_mcmc_exal_v2_canary",
  "remaining_failed_mcmc_al_v2_residual",
  "remaining_failed_mcmc_exal_v2_residual",
  "remaining_failed_mcmc_al_v2",
  "remaining_failed_mcmc_exal_v2",
  "remaining_failed_mcmc_al_v3_rescue_canary",
  "remaining_failed_mcmc_exal_v3_rescue_canary",
  "remaining_failed_mcmc_al_v3_rescue_residual",
  "remaining_failed_mcmc_exal_v3_rescue_residual",
  "remaining_failed_mcmc_al_v3_rescue",
  "remaining_failed_mcmc_exal_v3_rescue",
  "remaining_failed_mcmc_al_v3_rescue_extended_canary",
  "remaining_failed_mcmc_exal_v3_rescue_extended_canary",
  "remaining_failed_mcmc_al_v3_rescue_extended_residual",
  "remaining_failed_mcmc_exal_v3_rescue_extended_residual",
  "remaining_failed_mcmc_al_v3_rescue_extended",
  "remaining_failed_mcmc_exal_v3_rescue_extended",
  "remaining_failed_mcmc_exal_v3_qr_tightslice_canary",
  "remaining_failed_mcmc_exal_v3_qr_tightslice_residual",
  "remaining_failed_mcmc_exal_v3_qr_tightslice",
  "remaining_failed_mcmc_exal_v3_altcore_canary",
  "remaining_failed_mcmc_exal_v3_altcore_residual",
  "remaining_failed_mcmc_exal_v3_altcore"
)
phase_materializer_map <- list(
  smoke = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R"),
  vb = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R"),
  mcmc_ridge = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R"),
  mcmc_rhsns_tt500 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R"),
  mcmc_rhsns_tt5000 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R"),
  failed_mcmc_al = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  failed_mcmc_exal = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  failed_mcmc_al_sfreeze = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  failed_mcmc_exal_sfreeze = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  failed_mcmc_al_thetafreeze = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  failed_mcmc_exal_thetafreeze = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_failed_mcmc_grids.R"),
  single_root_probe_exal_tau_only = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  single_root_probe_exal_theta_tau = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  single_root_probe_exal_stau = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  single_root_probe_exal_theta_tau_rescue = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_triad_exal_tau_only = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_triad_exal_theta_tau = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_triad_al_tau_only = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_triad_al_theta_tau = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_completion_exal_tau_only = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  representative_completion_exal_theta_tau = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_single_root_probe_grids.R"),
  remaining_precision_pair_al_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_grids.R"),
  remaining_precision_pair_exal_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_pair_grids.R"),
  remaining_precision_matrix_al_qr_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_al_qr_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_al_diag_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_exal_qr_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_exal_qr_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_exal_qr_sig_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_matrix_exal_diag_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_matrix.R"),
  remaining_precision_code_al_ladder_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_precision_code_al_ladder_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_precision_code_al_eigen_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_precision_code_exal_ladder_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_precision_code_exal_ladder_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_precision_code_exal_eigen_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_precision_code_matrix.R"),
  remaining_hard_fail_latent_v_al = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_run_specific_remaining_fail_grids.R"),
  remaining_hard_fail_latent_v_exal = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_run_specific_remaining_fail_grids.R"),
  remaining_hard_fail_exal_ridge_precision_v1 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_run_specific_remaining_fail_grids.R"),
  remaining_hard_fail_exal_ridge_precision_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_run_specific_remaining_fail_grids.R"),
  remaining_failed_mcmc_al_v2_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_exal_v2_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_al_v2_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_exal_v2_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_al_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_exal_v2 = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v2_grids.R"),
  remaining_failed_mcmc_al_v3_rescue_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_al_v3_rescue_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_al_v3_rescue = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_al_v3_rescue_extended_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue_extended_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_al_v3_rescue_extended_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue_extended_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_al_v3_rescue_extended = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_rescue_extended = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_qr_tightslice_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_qr_tightslice = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_altcore_canary = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_altcore_residual = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  remaining_failed_mcmc_exal_v3_altcore = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_remaining_failed_mcmc_v3_grids.R"),
  full = file.path("scripts", "materialize_qdesn_dynamic_exdqlm_crossstudy_tau050_refreshed_main_grid.R")
)

defaults_path <- phase_defaults_map[[phase]]
materialize_status <- system2(
  "Rscript",
  phase_materializer_map[[phase]],
  stdout = "",
  stderr = ""
)
if (!identical(as.integer(materialize_status), 0L)) {
  quit(status = as.integer(materialize_status), save = "no")
}

workers <- suppressWarnings(as.integer(get_arg("--workers", NA_character_))[1L])
if (!is.finite(workers) || workers < 1L) {
  workers <- as.integer(phase_workers_map[[phase]])[1L]
}

grid_path <- phase_grid_map[[phase]]
methods_arg <- phase_methods_map[[phase]]
likelihoods_arg <- phase_likelihoods_map[[phase]]
git_sha <- trimws(system("git rev-parse --short HEAD", intern = TRUE))
run_tag <- as.character(get_arg(
  "--run-tag",
  sprintf("qdesn-dynamic-exdqlm-crossstudy-tau050-%s-%s__git-%s", phase, format(Sys.time(), "%Y%m%d-%H%M%S"), git_sha)
))[1L]

child_args <- c(
  "--defaults", defaults_path,
  "--grid", grid_path,
  "--methods", methods_arg,
  "--workers", as.character(workers),
  "--batch", "full",
  "--run-tag", run_tag
)
if (nzchar(trimws(as.character(likelihoods_arg %||% "")[1L]))) {
  child_args <- c(child_args, "--likelihoods", as.character(likelihoods_arg)[1L])
}
if (has_flag("--prepare-only")) child_args <- c(child_args, "--prepare-only")
if (has_flag("--refresh-grid")) child_args <- c(child_args, "--refresh-grid")
if (isTRUE(phase_is_subset) || has_flag("--allow-grid-subset")) child_args <- c(child_args, "--allow-grid-subset")
if (has_flag("--no-plots")) child_args <- c(child_args, "--no-plots")
if (has_flag("--quiet")) child_args <- c(child_args, "--quiet")

target_script <- if (has_flag("--prepare-only")) {
  file.path("scripts", "run_qdesn_dynamic_exdqlm_crossstudy_validation.R")
} else {
  file.path("scripts", "launch_qdesn_dynamic_exdqlm_crossstudy_validation.R")
}

status <- system2("Rscript", c(target_script, child_args), stdout = "", stderr = "")
quit(status = as.integer(status), save = "no")
