// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_gamma_bounds
NumericVector get_gamma_bounds(double p0);
RcppExport SEXP _exdqlm_get_gamma_bounds(SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_gamma_bounds(p0));
    return rcpp_result_gen;
END_RCPP
}
// dexal
double dexal(double x, double p0, double mu, double sigma, double gamma, bool log_);
RcppExport SEXP _exdqlm_dexal(SEXP xSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP log_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type log_(log_SEXP);
    rcpp_result_gen = Rcpp::wrap(dexal(x, p0, mu, sigma, gamma, log_));
    return rcpp_result_gen;
END_RCPP
}
// pexal
double pexal(double q, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_pexal(SEXP qSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pexal(q, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qexal
double qexal(double prob, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_qexal(SEXP probSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qexal(prob, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rexal
NumericVector rexal(int n, double p0, double mu, double sigma, double gamma);
RcppExport SEXP _exdqlm_rexal(SEXP nSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rexal(n, p0, mu, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}
// logDetCholesky
double logDetCholesky(const Eigen::MatrixXd& matrix);
RcppExport SEXP _exdqlm_logDetCholesky(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type matrix(matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(logDetCholesky(matrix));
    return rcpp_result_gen;
END_RCPP
}
// compute_cholesky
Rcpp::List compute_cholesky(const arma::mat& q, bool compute_sqrt_inverse);
RcppExport SEXP _exdqlm_compute_cholesky(SEXP qSEXP, SEXP compute_sqrt_inverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_sqrt_inverse(compute_sqrt_inverseSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cholesky(q, compute_sqrt_inverse));
    return rcpp_result_gen;
END_RCPP
}
// H_t_k_r
arma::mat H_t_k_r(const arma::cube& GG, int t, int k, int r);
RcppExport SEXP _exdqlm_H_t_k_r(SEXP GGSEXP, SEXP tSEXP, SEXP kSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(H_t_k_r(GG, t, k, r));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_cpp
List update_theta_cpp(const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const arma::mat& ex_f, const arma::cube& ex_q, const arma::cube& FF, const arma::mat& y, const arma::mat& ex_df_mat, const arma::mat& ex_df_mat_k, const arma::mat& Ones, int p, int J, int ppx, int TT, int k, int dM);
RcppExport SEXP _exdqlm_update_theta_cpp(SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP ex_fSEXP, SEXP ex_qSEXP, SEXP FFSEXP, SEXP ySEXP, SEXP ex_df_matSEXP, SEXP ex_df_mat_kSEXP, SEXP OnesSEXP, SEXP pSEXP, SEXP JSEXP, SEXP ppxSEXP, SEXP TTSEXP, SEXP kSEXP, SEXP dMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_f(ex_fSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ex_q(ex_qSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_df_mat(ex_df_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_df_mat_k(ex_df_mat_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ones(OnesSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type ppx(ppxSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type dM(dMSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_cpp(GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, ex_df_mat_k, Ones, p, J, ppx, TT, k, dM));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exdqlm_get_gamma_bounds", (DL_FUNC) &_exdqlm_get_gamma_bounds, 1},
    {"_exdqlm_dexal", (DL_FUNC) &_exdqlm_dexal, 6},
    {"_exdqlm_pexal", (DL_FUNC) &_exdqlm_pexal, 7},
    {"_exdqlm_qexal", (DL_FUNC) &_exdqlm_qexal, 7},
    {"_exdqlm_rexal", (DL_FUNC) &_exdqlm_rexal, 5},
    {"_exdqlm_logDetCholesky", (DL_FUNC) &_exdqlm_logDetCholesky, 1},
    {"_exdqlm_compute_cholesky", (DL_FUNC) &_exdqlm_compute_cholesky, 2},
    {"_exdqlm_H_t_k_r", (DL_FUNC) &_exdqlm_H_t_k_r, 4},
    {"_exdqlm_update_theta_cpp", (DL_FUNC) &_exdqlm_update_theta_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_exdqlm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
