// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_gamma_bounds
NumericVector get_gamma_bounds(double p0);
RcppExport SEXP _exdqlm_get_gamma_bounds(SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_gamma_bounds(p0));
    return rcpp_result_gen;
END_RCPP
}
// dexal
double dexal(double x, double p0, double mu, double sigma, double gamma, bool log_);
RcppExport SEXP _exdqlm_dexal(SEXP xSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP log_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type log_(log_SEXP);
    rcpp_result_gen = Rcpp::wrap(dexal(x, p0, mu, sigma, gamma, log_));
    return rcpp_result_gen;
END_RCPP
}
// pexal
double pexal(double q, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_pexal(SEXP qSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(pexal(q, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qexal
double qexal(double prob, double p0, double mu, double sigma, double gamma, bool lower_tail, bool log_p);
RcppExport SEXP _exdqlm_qexal(SEXP probSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prob(probSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qexal(prob, p0, mu, sigma, gamma, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rexal
NumericVector rexal(int n, double p0, double mu, double sigma, double gamma);
RcppExport SEXP _exdqlm_rexal(SEXP nSEXP, SEXP p0SEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(rexal(n, p0, mu, sigma, gamma));
    return rcpp_result_gen;
END_RCPP
}
// exal_loglik_from_mu_cpp
NumericMatrix exal_loglik_from_mu_cpp(const NumericVector& y, const NumericMatrix& mu_mat, const NumericVector& sigma_draws, const NumericVector& gamma_draws, const double p0);
RcppExport SEXP _exdqlm_exal_loglik_from_mu_cpp(SEXP ySEXP, SEXP mu_matSEXP, SEXP sigma_drawsSEXP, SEXP gamma_drawsSEXP, SEXP p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mu_mat(mu_matSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sigma_draws(sigma_drawsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type gamma_draws(gamma_drawsSEXP);
    Rcpp::traits::input_parameter< const double >::type p0(p0SEXP);
    rcpp_result_gen = Rcpp::wrap(exal_loglik_from_mu_cpp(y, mu_mat, sigma_draws, gamma_draws, p0));
    return rcpp_result_gen;
END_RCPP
}
// forecast_paths_cpp
Rcpp::List forecast_paths_cpp(Rcpp::List W_list, Rcpp::List Win_list, Rcpp::List Q_list, Rcpp::NumericVector alpha, int D, bool add_bias, Rcpp::NumericVector y_hist0, Rcpp::IntegerVector y_lags, Rcpp::List x_blocks, Rcpp::NumericMatrix beta, Rcpp::NumericVector sigma, Rcpp::NumericVector A_d, Rcpp::NumericVector B_d, Rcpp::NumericVector lam_d, Rcpp::NumericVector y_obs_vec, int H, int m_res, int p_res, bool standardize_inputs, double lag_center, double lag_scale, Rcpp::NumericVector win_scale_lags, std::string input_bound, double win_scale_global, double win_scale_bias, Rcpp::List scale_info, int act_f_code, int act_k_code, Rcpp::List origin_state, int res_lags, Rcpp::Nullable<Rcpp::NumericMatrix> res_lag_init, Rcpp::Nullable<Rcpp::NumericMatrix> s_draws, Rcpp::Nullable<Rcpp::NumericMatrix> v_draws, Rcpp::Nullable<Rcpp::NumericMatrix> z_draws, bool use_omp, Rcpp::Nullable<Rcpp::LogicalVector> Q_is_identity, bool decomp_mode, Rcpp::Nullable<Rcpp::NumericVector> decomp_trend, Rcpp::Nullable<Rcpp::NumericVector> decomp_seasonal, Rcpp::Nullable<Rcpp::NumericVector> decomp_regression, Rcpp::Nullable<Rcpp::NumericVector> decomp_transfer, Rcpp::Nullable<Rcpp::NumericVector> decomp_structured, Rcpp::Nullable<Rcpp::NumericVector> decomp_trend_init, Rcpp::Nullable<Rcpp::NumericVector> decomp_seasonal_init, Rcpp::Nullable<Rcpp::NumericVector> decomp_regression_init, Rcpp::Nullable<Rcpp::NumericVector> decomp_transfer_init, Rcpp::Nullable<Rcpp::NumericVector> decomp_residual_init, Rcpp::Nullable<Rcpp::IntegerVector> decomp_component_codes, int decomp_residual_mode);
RcppExport SEXP _exdqlm_forecast_paths_cpp(SEXP W_listSEXP, SEXP Win_listSEXP, SEXP Q_listSEXP, SEXP alphaSEXP, SEXP DSEXP, SEXP add_biasSEXP, SEXP y_hist0SEXP, SEXP y_lagsSEXP, SEXP x_blocksSEXP, SEXP betaSEXP, SEXP sigmaSEXP, SEXP A_dSEXP, SEXP B_dSEXP, SEXP lam_dSEXP, SEXP y_obs_vecSEXP, SEXP HSEXP, SEXP m_resSEXP, SEXP p_resSEXP, SEXP standardize_inputsSEXP, SEXP lag_centerSEXP, SEXP lag_scaleSEXP, SEXP win_scale_lagsSEXP, SEXP input_boundSEXP, SEXP win_scale_globalSEXP, SEXP win_scale_biasSEXP, SEXP scale_infoSEXP, SEXP act_f_codeSEXP, SEXP act_k_codeSEXP, SEXP origin_stateSEXP, SEXP res_lagsSEXP, SEXP res_lag_initSEXP, SEXP s_drawsSEXP, SEXP v_drawsSEXP, SEXP z_drawsSEXP, SEXP use_ompSEXP, SEXP Q_is_identitySEXP, SEXP decomp_modeSEXP, SEXP decomp_trendSEXP, SEXP decomp_seasonalSEXP, SEXP decomp_regressionSEXP, SEXP decomp_transferSEXP, SEXP decomp_structuredSEXP, SEXP decomp_trend_initSEXP, SEXP decomp_seasonal_initSEXP, SEXP decomp_regression_initSEXP, SEXP decomp_transfer_initSEXP, SEXP decomp_residual_initSEXP, SEXP decomp_component_codesSEXP, SEXP decomp_residual_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type W_list(W_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Win_list(Win_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Q_list(Q_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type add_bias(add_biasSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_hist0(y_hist0SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y_lags(y_lagsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type x_blocks(x_blocksSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type A_d(A_dSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type B_d(B_dSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lam_d(lam_dSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_obs_vec(y_obs_vecSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type m_res(m_resSEXP);
    Rcpp::traits::input_parameter< int >::type p_res(p_resSEXP);
    Rcpp::traits::input_parameter< bool >::type standardize_inputs(standardize_inputsSEXP);
    Rcpp::traits::input_parameter< double >::type lag_center(lag_centerSEXP);
    Rcpp::traits::input_parameter< double >::type lag_scale(lag_scaleSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type win_scale_lags(win_scale_lagsSEXP);
    Rcpp::traits::input_parameter< std::string >::type input_bound(input_boundSEXP);
    Rcpp::traits::input_parameter< double >::type win_scale_global(win_scale_globalSEXP);
    Rcpp::traits::input_parameter< double >::type win_scale_bias(win_scale_biasSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type scale_info(scale_infoSEXP);
    Rcpp::traits::input_parameter< int >::type act_f_code(act_f_codeSEXP);
    Rcpp::traits::input_parameter< int >::type act_k_code(act_k_codeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type origin_state(origin_stateSEXP);
    Rcpp::traits::input_parameter< int >::type res_lags(res_lagsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type res_lag_init(res_lag_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type s_draws(s_drawsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type v_draws(v_drawsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type z_draws(z_drawsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_omp(use_ompSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::LogicalVector> >::type Q_is_identity(Q_is_identitySEXP);
    Rcpp::traits::input_parameter< bool >::type decomp_mode(decomp_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_trend(decomp_trendSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_seasonal(decomp_seasonalSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_regression(decomp_regressionSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_transfer(decomp_transferSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_structured(decomp_structuredSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_trend_init(decomp_trend_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_seasonal_init(decomp_seasonal_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_regression_init(decomp_regression_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_transfer_init(decomp_transfer_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type decomp_residual_init(decomp_residual_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type decomp_component_codes(decomp_component_codesSEXP);
    Rcpp::traits::input_parameter< int >::type decomp_residual_mode(decomp_residual_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(forecast_paths_cpp(W_list, Win_list, Q_list, alpha, D, add_bias, y_hist0, y_lags, x_blocks, beta, sigma, A_d, B_d, lam_d, y_obs_vec, H, m_res, p_res, standardize_inputs, lag_center, lag_scale, win_scale_lags, input_bound, win_scale_global, win_scale_bias, scale_info, act_f_code, act_k_code, origin_state, res_lags, res_lag_init, s_draws, v_draws, z_draws, use_omp, Q_is_identity, decomp_mode, decomp_trend, decomp_seasonal, decomp_regression, decomp_transfer, decomp_structured, decomp_trend_init, decomp_seasonal_init, decomp_regression_init, decomp_transfer_init, decomp_residual_init, decomp_component_codes, decomp_residual_mode));
    return rcpp_result_gen;
END_RCPP
}
// logDetCholesky
double logDetCholesky(const Eigen::MatrixXd& matrix);
RcppExport SEXP _exdqlm_logDetCholesky(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type matrix(matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(logDetCholesky(matrix));
    return rcpp_result_gen;
END_RCPP
}
// compute_cholesky
Rcpp::List compute_cholesky(const arma::mat& q, bool compute_sqrt_inverse);
RcppExport SEXP _exdqlm_compute_cholesky(SEXP qSEXP, SEXP compute_sqrt_inverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type q(qSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_sqrt_inverse(compute_sqrt_inverseSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cholesky(q, compute_sqrt_inverse));
    return rcpp_result_gen;
END_RCPP
}
// H_t_k_r
arma::mat H_t_k_r(const arma::cube& GG, int t, int k, int r);
RcppExport SEXP _exdqlm_H_t_k_r(SEXP GGSEXP, SEXP tSEXP, SEXP kSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(H_t_k_r(GG, t, k, r));
    return rcpp_result_gen;
END_RCPP
}
// update_theta_cpp
List update_theta_cpp(const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const arma::mat& ex_f, const arma::cube& ex_q, const arma::cube& FF, const arma::mat& y, const arma::mat& ex_df_mat, const arma::mat& ex_df_mat_k, const arma::mat& Ones, int p, int J, int ppx, int TT, int k, int dM);
RcppExport SEXP _exdqlm_update_theta_cpp(SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP ex_fSEXP, SEXP ex_qSEXP, SEXP FFSEXP, SEXP ySEXP, SEXP ex_df_matSEXP, SEXP ex_df_mat_kSEXP, SEXP OnesSEXP, SEXP pSEXP, SEXP JSEXP, SEXP ppxSEXP, SEXP TTSEXP, SEXP kSEXP, SEXP dMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_f(ex_fSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type ex_q(ex_qSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_df_mat(ex_df_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ex_df_mat_k(ex_df_mat_kSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ones(OnesSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type ppx(ppxSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type dM(dMSEXP);
    rcpp_result_gen = Rcpp::wrap(update_theta_cpp(GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, ex_df_mat_k, Ones, p, J, ppx, TT, k, dM));
    return rcpp_result_gen;
END_RCPP
}
// dlm_ndlm_filter_smooth_cpp
Rcpp::List dlm_ndlm_filter_smooth_cpp(const arma::vec& y, const arma::mat& FF, const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const arma::vec& df, const arma::ivec& dim_df, const double l0, const double S0, const bool compute_smoothed, const bool return_intermediates, const double jitter);
RcppExport SEXP _exdqlm_dlm_ndlm_filter_smooth_cpp(SEXP ySEXP, SEXP FFSEXP, SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP dfSEXP, SEXP dim_dfSEXP, SEXP l0SEXP, SEXP S0SEXP, SEXP compute_smoothedSEXP, SEXP return_intermediatesSEXP, SEXP jitterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type dim_df(dim_dfSEXP);
    Rcpp::traits::input_parameter< const double >::type l0(l0SEXP);
    Rcpp::traits::input_parameter< const double >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_smoothed(compute_smoothedSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_intermediates(return_intermediatesSEXP);
    Rcpp::traits::input_parameter< const double >::type jitter(jitterSEXP);
    rcpp_result_gen = Rcpp::wrap(dlm_ndlm_filter_smooth_cpp(y, FF, GG, m0, C0, df, dim_df, l0, S0, compute_smoothed, return_intermediates, jitter));
    return rcpp_result_gen;
END_RCPP
}
// dlm_ndlm_structured_forecast_cpp
Rcpp::List dlm_ndlm_structured_forecast_cpp(const arma::cube& GG, const arma::mat& FF, const arma::vec& state_origin, const arma::ivec& idx_trend, const arma::ivec& idx_seasonal, const int origin_index, const int H);
RcppExport SEXP _exdqlm_dlm_ndlm_structured_forecast_cpp(SEXP GGSEXP, SEXP FFSEXP, SEXP state_originSEXP, SEXP idx_trendSEXP, SEXP idx_seasonalSEXP, SEXP origin_indexSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type state_origin(state_originSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type idx_trend(idx_trendSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type idx_seasonal(idx_seasonalSEXP);
    Rcpp::traits::input_parameter< const int >::type origin_index(origin_indexSEXP);
    Rcpp::traits::input_parameter< const int >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(dlm_ndlm_structured_forecast_cpp(GG, FF, state_origin, idx_trend, idx_seasonal, origin_index, H));
    return rcpp_result_gen;
END_RCPP
}
// sample_truncnorm
Rcpp::NumericMatrix sample_truncnorm(int n_samp, int TT, Rcpp::NumericVector sts_mu, Rcpp::NumericVector sts_sig2);
RcppExport SEXP _exdqlm_sample_truncnorm(SEXP n_sampSEXP, SEXP TTSEXP, SEXP sts_muSEXP, SEXP sts_sig2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sts_mu(sts_muSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sts_sig2(sts_sig2SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_truncnorm(n_samp, TT, sts_mu, sts_sig2));
    return rcpp_result_gen;
END_RCPP
}
// sample_gig_devroye_vector
Rcpp::NumericMatrix sample_gig_devroye_vector(int n_samples, double p, double a, Rcpp::NumericVector b_vec);
RcppExport SEXP _exdqlm_sample_gig_devroye_vector(SEXP n_samplesSEXP, SEXP pSEXP, SEXP aSEXP, SEXP b_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_vec(b_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_gig_devroye_vector(n_samples, p, a, b_vec));
    return rcpp_result_gen;
END_RCPP
}
// sample_multivariate_normal
arma::cube sample_multivariate_normal(int n_samp, int TT, arma::cube sC, arma::mat sm, int p, int J);
RcppExport SEXP _exdqlm_sample_multivariate_normal(SEXP n_sampSEXP, SEXP TTSEXP, SEXP sCSEXP, SEXP smSEXP, SEXP pSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC(sCSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm(smSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_multivariate_normal(n_samp, TT, sC, sm, p, J));
    return rcpp_result_gen;
END_RCPP
}
// samp_post_pred
arma::cube samp_post_pred(int n_samp, int TT, int p, int J, arma::cube samp_theta, arma::cube FF, arma::mat samp_sigma, double p0, arma::mat samp_gamma, arma::cube samp_sts);
RcppExport SEXP _exdqlm_samp_post_pred(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP samp_thetaSEXP, SEXP FFSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_stsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_theta(samp_thetaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_sts(samp_stsSEXP);
    rcpp_result_gen = Rcpp::wrap(samp_post_pred(n_samp, TT, p, J, samp_theta, FF, samp_sigma, p0, samp_gamma, samp_sts));
    return rcpp_result_gen;
END_RCPP
}
// generate_samples
Rcpp::List generate_samples(int n_samp, int TT, int p, int J, arma::cube FF, arma::cube sC, arma::mat sm, arma::mat samp_sigma, double p0, arma::mat samp_gamma, arma::cube samp_sts);
RcppExport SEXP _exdqlm_generate_samples(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP FFSEXP, SEXP sCSEXP, SEXP smSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_stsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC(sCSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm(smSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_sts(samp_stsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_samples(n_samp, TT, p, J, FF, sC, sm, samp_sigma, p0, samp_gamma, samp_sts));
    return rcpp_result_gen;
END_RCPP
}
// samp_post_pred_synth
Rcpp::List samp_post_pred_synth(int n_samp, int k_forecast, int p_ens, int J, arma::cube samp_theta_ens, arma::cube FF_ens, arma::mat samp_sigma, double p0, arma::mat samp_gamma, Rcpp::List samp_sts_ens);
RcppExport SEXP _exdqlm_samp_post_pred_synth(SEXP n_sampSEXP, SEXP k_forecastSEXP, SEXP p_ensSEXP, SEXP JSEXP, SEXP samp_theta_ensSEXP, SEXP FF_ensSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_sts_ensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type k_forecast(k_forecastSEXP);
    Rcpp::traits::input_parameter< int >::type p_ens(p_ensSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_theta_ens(samp_theta_ensSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF_ens(FF_ensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type samp_sts_ens(samp_sts_ensSEXP);
    rcpp_result_gen = Rcpp::wrap(samp_post_pred_synth(n_samp, k_forecast, p_ens, J, samp_theta_ens, FF_ens, samp_sigma, p0, samp_gamma, samp_sts_ens));
    return rcpp_result_gen;
END_RCPP
}
// generate_synth_samples
Rcpp::List generate_synth_samples(int n_samp, int TT, int p, int J, arma::cube FF, arma::cube sC, arma::mat sm, arma::mat samp_sigma, double p0, arma::mat samp_gamma, arma::cube samp_sts, Rcpp::List samp_sts_ens, int k_forecast, int p_ens, arma::cube FF_ens, arma::cube sC_ens, arma::mat sm_ens);
RcppExport SEXP _exdqlm_generate_synth_samples(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP FFSEXP, SEXP sCSEXP, SEXP smSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_stsSEXP, SEXP samp_sts_ensSEXP, SEXP k_forecastSEXP, SEXP p_ensSEXP, SEXP FF_ensSEXP, SEXP sC_ensSEXP, SEXP sm_ensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC(sCSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm(smSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_sts(samp_stsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type samp_sts_ens(samp_sts_ensSEXP);
    Rcpp::traits::input_parameter< int >::type k_forecast(k_forecastSEXP);
    Rcpp::traits::input_parameter< int >::type p_ens(p_ensSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF_ens(FF_ensSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC_ens(sC_ensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm_ens(sm_ensSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_synth_samples(n_samp, TT, p, J, FF, sC, sm, samp_sigma, p0, samp_gamma, samp_sts, samp_sts_ens, k_forecast, p_ens, FF_ens, sC_ens, sm_ens));
    return rcpp_result_gen;
END_RCPP
}
// generate_synth_samples_retro_part
Rcpp::List generate_synth_samples_retro_part(int n_samp, int TT, int p, int J, arma::cube sC, arma::mat sm);
RcppExport SEXP _exdqlm_generate_synth_samples_retro_part(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP sCSEXP, SEXP smSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC(sCSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm(smSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_synth_samples_retro_part(n_samp, TT, p, J, sC, sm));
    return rcpp_result_gen;
END_RCPP
}
// generate_synth_samples_forecast_part
Rcpp::List generate_synth_samples_forecast_part(int n_samp, int J, int k_forecast, int p_ens, arma::cube sC_ens, arma::mat sm_ens);
RcppExport SEXP _exdqlm_generate_synth_samples_forecast_part(SEXP n_sampSEXP, SEXP JSEXP, SEXP k_forecastSEXP, SEXP p_ensSEXP, SEXP sC_ensSEXP, SEXP sm_ensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type k_forecast(k_forecastSEXP);
    Rcpp::traits::input_parameter< int >::type p_ens(p_ensSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC_ens(sC_ensSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm_ens(sm_ensSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_synth_samples_forecast_part(n_samp, J, k_forecast, p_ens, sC_ens, sm_ens));
    return rcpp_result_gen;
END_RCPP
}
// samp_post_pred_extended
arma::cube samp_post_pred_extended(int n_samp, int TT, int p, int J, arma::cube samp_theta, arma::cube FF, arma::mat samp_sigma, double p0, arma::mat samp_gamma, arma::cube samp_sts, arma::cube samp_uts);
RcppExport SEXP _exdqlm_samp_post_pred_extended(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP samp_thetaSEXP, SEXP FFSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_stsSEXP, SEXP samp_utsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_theta(samp_thetaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_sts(samp_stsSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_uts(samp_utsSEXP);
    rcpp_result_gen = Rcpp::wrap(samp_post_pred_extended(n_samp, TT, p, J, samp_theta, FF, samp_sigma, p0, samp_gamma, samp_sts, samp_uts));
    return rcpp_result_gen;
END_RCPP
}
// generate_samples_ext
Rcpp::List generate_samples_ext(int n_samp, int TT, int p, int J, arma::cube FF, arma::cube sC, arma::mat sm, arma::mat samp_sigma, double p0, arma::mat samp_gamma, arma::cube samp_sts, arma::cube samp_uts);
RcppExport SEXP _exdqlm_generate_samples_ext(SEXP n_sampSEXP, SEXP TTSEXP, SEXP pSEXP, SEXP JSEXP, SEXP FFSEXP, SEXP sCSEXP, SEXP smSEXP, SEXP samp_sigmaSEXP, SEXP p0SEXP, SEXP samp_gammaSEXP, SEXP samp_stsSEXP, SEXP samp_utsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samp(n_sampSEXP);
    Rcpp::traits::input_parameter< int >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type sC(sCSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sm(smSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_sigma(samp_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type samp_gamma(samp_gammaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_sts(samp_stsSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type samp_uts(samp_utsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_samples_ext(n_samp, TT, p, J, FF, sC, sm, samp_sigma, p0, samp_gamma, samp_sts, samp_uts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exdqlm_get_gamma_bounds", (DL_FUNC) &_exdqlm_get_gamma_bounds, 1},
    {"_exdqlm_dexal", (DL_FUNC) &_exdqlm_dexal, 6},
    {"_exdqlm_pexal", (DL_FUNC) &_exdqlm_pexal, 7},
    {"_exdqlm_qexal", (DL_FUNC) &_exdqlm_qexal, 7},
    {"_exdqlm_rexal", (DL_FUNC) &_exdqlm_rexal, 5},
    {"_exdqlm_exal_loglik_from_mu_cpp", (DL_FUNC) &_exdqlm_exal_loglik_from_mu_cpp, 5},
    {"_exdqlm_forecast_paths_cpp", (DL_FUNC) &_exdqlm_forecast_paths_cpp, 49},
    {"_exdqlm_logDetCholesky", (DL_FUNC) &_exdqlm_logDetCholesky, 1},
    {"_exdqlm_compute_cholesky", (DL_FUNC) &_exdqlm_compute_cholesky, 2},
    {"_exdqlm_H_t_k_r", (DL_FUNC) &_exdqlm_H_t_k_r, 4},
    {"_exdqlm_update_theta_cpp", (DL_FUNC) &_exdqlm_update_theta_cpp, 16},
    {"_exdqlm_dlm_ndlm_filter_smooth_cpp", (DL_FUNC) &_exdqlm_dlm_ndlm_filter_smooth_cpp, 12},
    {"_exdqlm_dlm_ndlm_structured_forecast_cpp", (DL_FUNC) &_exdqlm_dlm_ndlm_structured_forecast_cpp, 7},
    {"_exdqlm_sample_truncnorm", (DL_FUNC) &_exdqlm_sample_truncnorm, 4},
    {"_exdqlm_sample_gig_devroye_vector", (DL_FUNC) &_exdqlm_sample_gig_devroye_vector, 4},
    {"_exdqlm_sample_multivariate_normal", (DL_FUNC) &_exdqlm_sample_multivariate_normal, 6},
    {"_exdqlm_samp_post_pred", (DL_FUNC) &_exdqlm_samp_post_pred, 10},
    {"_exdqlm_generate_samples", (DL_FUNC) &_exdqlm_generate_samples, 11},
    {"_exdqlm_samp_post_pred_synth", (DL_FUNC) &_exdqlm_samp_post_pred_synth, 10},
    {"_exdqlm_generate_synth_samples", (DL_FUNC) &_exdqlm_generate_synth_samples, 17},
    {"_exdqlm_generate_synth_samples_retro_part", (DL_FUNC) &_exdqlm_generate_synth_samples_retro_part, 6},
    {"_exdqlm_generate_synth_samples_forecast_part", (DL_FUNC) &_exdqlm_generate_synth_samples_forecast_part, 6},
    {"_exdqlm_samp_post_pred_extended", (DL_FUNC) &_exdqlm_samp_post_pred_extended, 11},
    {"_exdqlm_generate_samples_ext", (DL_FUNC) &_exdqlm_generate_samples_ext, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_exdqlm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
