# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_gamma_bounds_cpp <- function(p0) {
    .Call(`_exdqlm_get_gamma_bounds`, p0)
}

dexal_cpp <- function(x, p0 = 0.5, mu = 0.0, sigma = 1.0, gamma = 0.0, log_ = FALSE) {
    .Call(`_exdqlm_dexal`, x, p0, mu, sigma, gamma, log_)
}

pexal_cpp <- function(q, p0 = 0.5, mu = 0.0, sigma = 1.0, gamma = 0.0, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_exdqlm_pexal`, q, p0, mu, sigma, gamma, lower_tail, log_p)
}

qexal_cpp <- function(prob, p0 = 0.5, mu = 0.0, sigma = 1.0, gamma = 0.0, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_exdqlm_qexal`, prob, p0, mu, sigma, gamma, lower_tail, log_p)
}

rexal_cpp <- function(n, p0 = 0.5, mu = 0.0, sigma = 1.0, gamma = 0.0) {
    .Call(`_exdqlm_rexal`, n, p0, mu, sigma, gamma)
}

logDetCholesky <- function(matrix) {
    .Call(`_exdqlm_logDetCholesky`, matrix)
}

compute_cholesky <- function(q, compute_sqrt_inverse = FALSE) {
    .Call(`_exdqlm_compute_cholesky`, q, compute_sqrt_inverse)
}

H_t_k_r <- function(GG, t, k, r) {
    .Call(`_exdqlm_H_t_k_r`, GG, t, k, r)
}

update_theta_cpp <- function(GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, ex_df_mat_k, Ones, p, J, ppx, TT, k, dM) {
    .Call(`_exdqlm_update_theta_cpp`, GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, ex_df_mat_k, Ones, p, J, ppx, TT, k, dM)
}

